-- Ordnet bestehende Karten den festen Themen und Baugruppen zu (Stand OPL 04.10.2026, #1 bis #132).
-- Thema: nur wenn es noch kein festes Thema ist; ein spezifisches altes Thema wird vor das
-- To Do gesetzt (allgemeine wie CAD oder Montage entfallen). Baugruppe: nur wenn noch leer.
-- Pro geaenderter Karte ein Eintrag im Aenderungsprotokoll. Mehrfaches Ausfuehren aendert nichts mehr.
INSERT INTO changelog (nr, text, wann, wer)
SELECT e.nr,
       'Umstellung feste Themen:' ||
       CASE WHEN e.thema NOT IN ('Kollision & Bauraum', 'Kabel & Steckverbinder', 'Montage & Service', 'Verbindungstechnik & Toleranzen', 'Poka Yoke & Varianten', 'Auslegung & Simulation', 'Thermik', 'Elektronik & Software', 'BOM/CAD & Dokumentation', 'Industrialisierung & Design') THEN ' Thema → "' || m.column2 || '"' ELSE '' END ||
       CASE WHEN COALESCE(e.baugruppe,'') = '' THEN ' Baugruppe → "' || m.column3 || '"' ELSE '' END,
       strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'Wartung'
FROM entries e JOIN (VALUES
  (1, 'Auslegung & Simulation', 'Übergreifend'),
  (2, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (3, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (4, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (5, 'Auslegung & Simulation', 'Übergreifend'),
  (6, 'Auslegung & Simulation', 'Übergreifend'),
  (7, 'Auslegung & Simulation', 'Übergreifend'),
  (8, 'Poka Yoke & Varianten', 'Übergreifend'),
  (9, 'Kabel & Steckverbinder', 'Übergreifend'),
  (10, 'Kabel & Steckverbinder', 'Übergreifend'),
  (11, 'Montage & Service', 'Übergreifend'),
  (12, 'Auslegung & Simulation', 'Arm'),
  (13, 'Kollision & Bauraum', 'Übergreifend'),
  (14, 'Auslegung & Simulation', 'Übergreifend'),
  (15, 'Thermik', 'Übergreifend'),
  (16, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (17, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (18, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (19, 'Montage & Service', 'Übergreifend'),
  (20, 'Elektronik & Software', 'Torso'),
  (21, 'Auslegung & Simulation', 'Torso'),
  (22, 'BOM/CAD & Dokumentation', 'Torso'),
  (23, 'Auslegung & Simulation', 'Kopf'),
  (24, 'Montage & Service', 'Übergreifend'),
  (25, 'Industrialisierung & Design', 'Übergreifend'),
  (26, 'Kollision & Bauraum', 'Bein'),
  (27, 'Kollision & Bauraum', 'Torso'),
  (28, 'Industrialisierung & Design', 'Übergreifend'),
  (29, 'Industrialisierung & Design', 'Bein'),
  (30, 'Elektronik & Software', 'Torso'),
  (31, 'Elektronik & Software', 'Torso'),
  (32, 'Elektronik & Software', 'Übergreifend'),
  (33, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (34, 'Industrialisierung & Design', 'Pelvis/Hüfte'),
  (35, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (36, 'Kollision & Bauraum', 'Übergreifend'),
  (37, 'Thermik', 'Torso'),
  (38, 'Auslegung & Simulation', 'Kopf'),
  (39, 'Auslegung & Simulation', 'Übergreifend'),
  (40, 'Auslegung & Simulation', 'Übergreifend'),
  (41, 'Auslegung & Simulation', 'Übergreifend'),
  (42, 'Kollision & Bauraum', 'Fuß'),
  (43, 'Kollision & Bauraum', 'Übergreifend'),
  (44, 'Montage & Service', 'Torso'),
  (45, 'Kabel & Steckverbinder', 'Übergreifend'),
  (46, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (47, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (48, 'Poka Yoke & Varianten', 'Bein'),
  (49, 'Industrialisierung & Design', 'Übergreifend'),
  (50, 'Elektronik & Software', 'Übergreifend'),
  (51, 'Industrialisierung & Design', 'Übergreifend'),
  (52, 'Thermik', 'Übergreifend'),
  (53, 'BOM/CAD & Dokumentation', 'Kopf'),
  (54, 'Kabel & Steckverbinder', 'Übergreifend'),
  (55, 'Kabel & Steckverbinder', 'Übergreifend'),
  (56, 'Industrialisierung & Design', 'Übergreifend'),
  (57, 'Kollision & Bauraum', 'Bein'),
  (58, 'Kollision & Bauraum', 'Bein'),
  (59, 'Kollision & Bauraum', 'Bein'),
  (60, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (61, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (62, 'Kollision & Bauraum', 'Bein'),
  (63, 'Verbindungstechnik & Toleranzen', 'Pelvis/Hüfte'),
  (64, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (65, 'Kabel & Steckverbinder', 'Torso'),
  (66, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (67, 'Thermik', 'Torso'),
  (68, 'Industrialisierung & Design', 'Bein'),
  (69, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (70, 'Kabel & Steckverbinder', 'Bein'),
  (71, 'Industrialisierung & Design', 'Arm'),
  (72, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (73, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (74, 'Kollision & Bauraum', 'Torso'),
  (75, 'Kabel & Steckverbinder', 'Arm'),
  (76, 'Kollision & Bauraum', 'Arm'),
  (77, 'Poka Yoke & Varianten', 'Übergreifend'),
  (78, 'Kollision & Bauraum', 'Arm'),
  (79, 'Montage & Service', 'Übergreifend'),
  (80, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (81, 'Kollision & Bauraum', 'Arm'),
  (82, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (83, 'Kabel & Steckverbinder', 'Übergreifend'),
  (84, 'Kabel & Steckverbinder', 'Bein'),
  (85, 'Kabel & Steckverbinder', 'Arm'),
  (86, 'Kollision & Bauraum', 'Arm'),
  (87, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (88, 'Verbindungstechnik & Toleranzen', 'Fuß'),
  (89, 'Poka Yoke & Varianten', 'Pelvis/Hüfte'),
  (90, 'Verbindungstechnik & Toleranzen', 'Pelvis/Hüfte'),
  (91, 'Montage & Service', 'Bein'),
  (92, 'Kollision & Bauraum', 'Bein'),
  (93, 'Montage & Service', 'Bein'),
  (94, 'Montage & Service', 'Übergreifend'),
  (95, 'Kollision & Bauraum', 'Bein'),
  (96, 'Montage & Service', 'Bein'),
  (97, 'Poka Yoke & Varianten', 'Arm'),
  (98, 'Kollision & Bauraum', 'Arm'),
  (99, 'Kabel & Steckverbinder', 'Arm'),
  (100, 'Kabel & Steckverbinder', 'Übergreifend'),
  (101, 'Montage & Service', 'Arm'),
  (102, 'Montage & Service', 'Arm'),
  (103, 'Poka Yoke & Varianten', 'Arm'),
  (104, 'BOM/CAD & Dokumentation', 'Arm'),
  (105, 'Montage & Service', 'Bein'),
  (106, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (107, 'Industrialisierung & Design', 'Übergreifend'),
  (108, 'Kollision & Bauraum', 'Arm'),
  (109, 'Kollision & Bauraum', 'Arm'),
  (110, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (111, 'Poka Yoke & Varianten', 'Übergreifend'),
  (112, 'Montage & Service', 'Übergreifend'),
  (113, 'Kabel & Steckverbinder', 'Arm'),
  (114, 'Kabel & Steckverbinder', 'Arm'),
  (115, 'Kabel & Steckverbinder', 'Arm'),
  (116, 'Kabel & Steckverbinder', 'Übergreifend'),
  (117, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (118, 'Montage & Service', 'Übergreifend'),
  (119, 'Kabel & Steckverbinder', 'Arm'),
  (120, 'Kollision & Bauraum', 'Bein'),
  (121, 'Poka Yoke & Varianten', 'Pelvis/Hüfte'),
  (122, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (123, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (124, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (125, 'Montage & Service', 'Arm'),
  (126, 'Montage & Service', 'Arm'),
  (127, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (128, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (129, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (130, 'Industrialisierung & Design', 'Übergreifend'),
  (131, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (132, 'Industrialisierung & Design', 'Übergreifend')
) AS m ON e.nr = m.column1
WHERE e.thema NOT IN ('Kollision & Bauraum', 'Kabel & Steckverbinder', 'Montage & Service', 'Verbindungstechnik & Toleranzen', 'Poka Yoke & Varianten', 'Auslegung & Simulation', 'Thermik', 'Elektronik & Software', 'BOM/CAD & Dokumentation', 'Industrialisierung & Design') OR COALESCE(e.baugruppe,'') = '';

UPDATE entries SET
  todo = CASE WHEN entries.thema <> '' AND entries.thema NOT IN ('CAD', 'Montage', 'Kabel', 'Design', 'Schrauben', 'Berechnung', 'Passung', 'Kollision', 'Elektrik', 'Thermik', 'Lagerung', 'Simulation', 'Material', 'Design-Regel')
              AND substr(COALESCE(entries.todo,''), 1, length(entries.thema)) <> entries.thema
         THEN entries.thema || CASE WHEN COALESCE(entries.todo,'') = '' THEN '' ELSE ': ' || entries.todo END
         ELSE entries.todo END,
  thema = m.column2
FROM (VALUES
  (1, 'Auslegung & Simulation', 'Übergreifend'),
  (2, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (3, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (4, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (5, 'Auslegung & Simulation', 'Übergreifend'),
  (6, 'Auslegung & Simulation', 'Übergreifend'),
  (7, 'Auslegung & Simulation', 'Übergreifend'),
  (8, 'Poka Yoke & Varianten', 'Übergreifend'),
  (9, 'Kabel & Steckverbinder', 'Übergreifend'),
  (10, 'Kabel & Steckverbinder', 'Übergreifend'),
  (11, 'Montage & Service', 'Übergreifend'),
  (12, 'Auslegung & Simulation', 'Arm'),
  (13, 'Kollision & Bauraum', 'Übergreifend'),
  (14, 'Auslegung & Simulation', 'Übergreifend'),
  (15, 'Thermik', 'Übergreifend'),
  (16, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (17, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (18, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (19, 'Montage & Service', 'Übergreifend'),
  (20, 'Elektronik & Software', 'Torso'),
  (21, 'Auslegung & Simulation', 'Torso'),
  (22, 'BOM/CAD & Dokumentation', 'Torso'),
  (23, 'Auslegung & Simulation', 'Kopf'),
  (24, 'Montage & Service', 'Übergreifend'),
  (25, 'Industrialisierung & Design', 'Übergreifend'),
  (26, 'Kollision & Bauraum', 'Bein'),
  (27, 'Kollision & Bauraum', 'Torso'),
  (28, 'Industrialisierung & Design', 'Übergreifend'),
  (29, 'Industrialisierung & Design', 'Bein'),
  (30, 'Elektronik & Software', 'Torso'),
  (31, 'Elektronik & Software', 'Torso'),
  (32, 'Elektronik & Software', 'Übergreifend'),
  (33, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (34, 'Industrialisierung & Design', 'Pelvis/Hüfte'),
  (35, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (36, 'Kollision & Bauraum', 'Übergreifend'),
  (37, 'Thermik', 'Torso'),
  (38, 'Auslegung & Simulation', 'Kopf'),
  (39, 'Auslegung & Simulation', 'Übergreifend'),
  (40, 'Auslegung & Simulation', 'Übergreifend'),
  (41, 'Auslegung & Simulation', 'Übergreifend'),
  (42, 'Kollision & Bauraum', 'Fuß'),
  (43, 'Kollision & Bauraum', 'Übergreifend'),
  (44, 'Montage & Service', 'Torso'),
  (45, 'Kabel & Steckverbinder', 'Übergreifend'),
  (46, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (47, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (48, 'Poka Yoke & Varianten', 'Bein'),
  (49, 'Industrialisierung & Design', 'Übergreifend'),
  (50, 'Elektronik & Software', 'Übergreifend'),
  (51, 'Industrialisierung & Design', 'Übergreifend'),
  (52, 'Thermik', 'Übergreifend'),
  (53, 'BOM/CAD & Dokumentation', 'Kopf'),
  (54, 'Kabel & Steckverbinder', 'Übergreifend'),
  (55, 'Kabel & Steckverbinder', 'Übergreifend'),
  (56, 'Industrialisierung & Design', 'Übergreifend'),
  (57, 'Kollision & Bauraum', 'Bein'),
  (58, 'Kollision & Bauraum', 'Bein'),
  (59, 'Kollision & Bauraum', 'Bein'),
  (60, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (61, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (62, 'Kollision & Bauraum', 'Bein'),
  (63, 'Verbindungstechnik & Toleranzen', 'Pelvis/Hüfte'),
  (64, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (65, 'Kabel & Steckverbinder', 'Torso'),
  (66, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (67, 'Thermik', 'Torso'),
  (68, 'Industrialisierung & Design', 'Bein'),
  (69, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (70, 'Kabel & Steckverbinder', 'Bein'),
  (71, 'Industrialisierung & Design', 'Arm'),
  (72, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (73, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (74, 'Kollision & Bauraum', 'Torso'),
  (75, 'Kabel & Steckverbinder', 'Arm'),
  (76, 'Kollision & Bauraum', 'Arm'),
  (77, 'Poka Yoke & Varianten', 'Übergreifend'),
  (78, 'Kollision & Bauraum', 'Arm'),
  (79, 'Montage & Service', 'Übergreifend'),
  (80, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (81, 'Kollision & Bauraum', 'Arm'),
  (82, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (83, 'Kabel & Steckverbinder', 'Übergreifend'),
  (84, 'Kabel & Steckverbinder', 'Bein'),
  (85, 'Kabel & Steckverbinder', 'Arm'),
  (86, 'Kollision & Bauraum', 'Arm'),
  (87, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (88, 'Verbindungstechnik & Toleranzen', 'Fuß'),
  (89, 'Poka Yoke & Varianten', 'Pelvis/Hüfte'),
  (90, 'Verbindungstechnik & Toleranzen', 'Pelvis/Hüfte'),
  (91, 'Montage & Service', 'Bein'),
  (92, 'Kollision & Bauraum', 'Bein'),
  (93, 'Montage & Service', 'Bein'),
  (94, 'Montage & Service', 'Übergreifend'),
  (95, 'Kollision & Bauraum', 'Bein'),
  (96, 'Montage & Service', 'Bein'),
  (97, 'Poka Yoke & Varianten', 'Arm'),
  (98, 'Kollision & Bauraum', 'Arm'),
  (99, 'Kabel & Steckverbinder', 'Arm'),
  (100, 'Kabel & Steckverbinder', 'Übergreifend'),
  (101, 'Montage & Service', 'Arm'),
  (102, 'Montage & Service', 'Arm'),
  (103, 'Poka Yoke & Varianten', 'Arm'),
  (104, 'BOM/CAD & Dokumentation', 'Arm'),
  (105, 'Montage & Service', 'Bein'),
  (106, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (107, 'Industrialisierung & Design', 'Übergreifend'),
  (108, 'Kollision & Bauraum', 'Arm'),
  (109, 'Kollision & Bauraum', 'Arm'),
  (110, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (111, 'Poka Yoke & Varianten', 'Übergreifend'),
  (112, 'Montage & Service', 'Übergreifend'),
  (113, 'Kabel & Steckverbinder', 'Arm'),
  (114, 'Kabel & Steckverbinder', 'Arm'),
  (115, 'Kabel & Steckverbinder', 'Arm'),
  (116, 'Kabel & Steckverbinder', 'Übergreifend'),
  (117, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (118, 'Montage & Service', 'Übergreifend'),
  (119, 'Kabel & Steckverbinder', 'Arm'),
  (120, 'Kollision & Bauraum', 'Bein'),
  (121, 'Poka Yoke & Varianten', 'Pelvis/Hüfte'),
  (122, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (123, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (124, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (125, 'Montage & Service', 'Arm'),
  (126, 'Montage & Service', 'Arm'),
  (127, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (128, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (129, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (130, 'Industrialisierung & Design', 'Übergreifend'),
  (131, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (132, 'Industrialisierung & Design', 'Übergreifend')
) AS m
WHERE entries.nr = m.column1 AND entries.thema NOT IN ('Kollision & Bauraum', 'Kabel & Steckverbinder', 'Montage & Service', 'Verbindungstechnik & Toleranzen', 'Poka Yoke & Varianten', 'Auslegung & Simulation', 'Thermik', 'Elektronik & Software', 'BOM/CAD & Dokumentation', 'Industrialisierung & Design');

UPDATE entries SET baugruppe = m.column3
FROM (VALUES
  (1, 'Auslegung & Simulation', 'Übergreifend'),
  (2, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (3, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (4, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (5, 'Auslegung & Simulation', 'Übergreifend'),
  (6, 'Auslegung & Simulation', 'Übergreifend'),
  (7, 'Auslegung & Simulation', 'Übergreifend'),
  (8, 'Poka Yoke & Varianten', 'Übergreifend'),
  (9, 'Kabel & Steckverbinder', 'Übergreifend'),
  (10, 'Kabel & Steckverbinder', 'Übergreifend'),
  (11, 'Montage & Service', 'Übergreifend'),
  (12, 'Auslegung & Simulation', 'Arm'),
  (13, 'Kollision & Bauraum', 'Übergreifend'),
  (14, 'Auslegung & Simulation', 'Übergreifend'),
  (15, 'Thermik', 'Übergreifend'),
  (16, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (17, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (18, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (19, 'Montage & Service', 'Übergreifend'),
  (20, 'Elektronik & Software', 'Torso'),
  (21, 'Auslegung & Simulation', 'Torso'),
  (22, 'BOM/CAD & Dokumentation', 'Torso'),
  (23, 'Auslegung & Simulation', 'Kopf'),
  (24, 'Montage & Service', 'Übergreifend'),
  (25, 'Industrialisierung & Design', 'Übergreifend'),
  (26, 'Kollision & Bauraum', 'Bein'),
  (27, 'Kollision & Bauraum', 'Torso'),
  (28, 'Industrialisierung & Design', 'Übergreifend'),
  (29, 'Industrialisierung & Design', 'Bein'),
  (30, 'Elektronik & Software', 'Torso'),
  (31, 'Elektronik & Software', 'Torso'),
  (32, 'Elektronik & Software', 'Übergreifend'),
  (33, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (34, 'Industrialisierung & Design', 'Pelvis/Hüfte'),
  (35, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (36, 'Kollision & Bauraum', 'Übergreifend'),
  (37, 'Thermik', 'Torso'),
  (38, 'Auslegung & Simulation', 'Kopf'),
  (39, 'Auslegung & Simulation', 'Übergreifend'),
  (40, 'Auslegung & Simulation', 'Übergreifend'),
  (41, 'Auslegung & Simulation', 'Übergreifend'),
  (42, 'Kollision & Bauraum', 'Fuß'),
  (43, 'Kollision & Bauraum', 'Übergreifend'),
  (44, 'Montage & Service', 'Torso'),
  (45, 'Kabel & Steckverbinder', 'Übergreifend'),
  (46, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (47, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (48, 'Poka Yoke & Varianten', 'Bein'),
  (49, 'Industrialisierung & Design', 'Übergreifend'),
  (50, 'Elektronik & Software', 'Übergreifend'),
  (51, 'Industrialisierung & Design', 'Übergreifend'),
  (52, 'Thermik', 'Übergreifend'),
  (53, 'BOM/CAD & Dokumentation', 'Kopf'),
  (54, 'Kabel & Steckverbinder', 'Übergreifend'),
  (55, 'Kabel & Steckverbinder', 'Übergreifend'),
  (56, 'Industrialisierung & Design', 'Übergreifend'),
  (57, 'Kollision & Bauraum', 'Bein'),
  (58, 'Kollision & Bauraum', 'Bein'),
  (59, 'Kollision & Bauraum', 'Bein'),
  (60, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (61, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (62, 'Kollision & Bauraum', 'Bein'),
  (63, 'Verbindungstechnik & Toleranzen', 'Pelvis/Hüfte'),
  (64, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (65, 'Kabel & Steckverbinder', 'Torso'),
  (66, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (67, 'Thermik', 'Torso'),
  (68, 'Industrialisierung & Design', 'Bein'),
  (69, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (70, 'Kabel & Steckverbinder', 'Bein'),
  (71, 'Industrialisierung & Design', 'Arm'),
  (72, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (73, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (74, 'Kollision & Bauraum', 'Torso'),
  (75, 'Kabel & Steckverbinder', 'Arm'),
  (76, 'Kollision & Bauraum', 'Arm'),
  (77, 'Poka Yoke & Varianten', 'Übergreifend'),
  (78, 'Kollision & Bauraum', 'Arm'),
  (79, 'Montage & Service', 'Übergreifend'),
  (80, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (81, 'Kollision & Bauraum', 'Arm'),
  (82, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (83, 'Kabel & Steckverbinder', 'Übergreifend'),
  (84, 'Kabel & Steckverbinder', 'Bein'),
  (85, 'Kabel & Steckverbinder', 'Arm'),
  (86, 'Kollision & Bauraum', 'Arm'),
  (87, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (88, 'Verbindungstechnik & Toleranzen', 'Fuß'),
  (89, 'Poka Yoke & Varianten', 'Pelvis/Hüfte'),
  (90, 'Verbindungstechnik & Toleranzen', 'Pelvis/Hüfte'),
  (91, 'Montage & Service', 'Bein'),
  (92, 'Kollision & Bauraum', 'Bein'),
  (93, 'Montage & Service', 'Bein'),
  (94, 'Montage & Service', 'Übergreifend'),
  (95, 'Kollision & Bauraum', 'Bein'),
  (96, 'Montage & Service', 'Bein'),
  (97, 'Poka Yoke & Varianten', 'Arm'),
  (98, 'Kollision & Bauraum', 'Arm'),
  (99, 'Kabel & Steckverbinder', 'Arm'),
  (100, 'Kabel & Steckverbinder', 'Übergreifend'),
  (101, 'Montage & Service', 'Arm'),
  (102, 'Montage & Service', 'Arm'),
  (103, 'Poka Yoke & Varianten', 'Arm'),
  (104, 'BOM/CAD & Dokumentation', 'Arm'),
  (105, 'Montage & Service', 'Bein'),
  (106, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (107, 'Industrialisierung & Design', 'Übergreifend'),
  (108, 'Kollision & Bauraum', 'Arm'),
  (109, 'Kollision & Bauraum', 'Arm'),
  (110, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (111, 'Poka Yoke & Varianten', 'Übergreifend'),
  (112, 'Montage & Service', 'Übergreifend'),
  (113, 'Kabel & Steckverbinder', 'Arm'),
  (114, 'Kabel & Steckverbinder', 'Arm'),
  (115, 'Kabel & Steckverbinder', 'Arm'),
  (116, 'Kabel & Steckverbinder', 'Übergreifend'),
  (117, 'Verbindungstechnik & Toleranzen', 'Bein'),
  (118, 'Montage & Service', 'Übergreifend'),
  (119, 'Kabel & Steckverbinder', 'Arm'),
  (120, 'Kollision & Bauraum', 'Bein'),
  (121, 'Poka Yoke & Varianten', 'Pelvis/Hüfte'),
  (122, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (123, 'BOM/CAD & Dokumentation', 'Übergreifend'),
  (124, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (125, 'Montage & Service', 'Arm'),
  (126, 'Montage & Service', 'Arm'),
  (127, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (128, 'Kollision & Bauraum', 'Pelvis/Hüfte'),
  (129, 'Verbindungstechnik & Toleranzen', 'Arm'),
  (130, 'Industrialisierung & Design', 'Übergreifend'),
  (131, 'Verbindungstechnik & Toleranzen', 'Übergreifend'),
  (132, 'Industrialisierung & Design', 'Übergreifend')
) AS m
WHERE entries.nr = m.column1 AND COALESCE(entries.baugruppe,'') = '';
